export const siteConfig = {
  title: 'Dante Calderon',
  subtitle: 'TypeScript / Node.js Developer',
  description: `Hi, I'm Dante Calderon, I am passionate about Nodejs.`,
  siteUrl: 'https://dantecalderon.com',
  disqusShortname: 'dantecalderon',
  githubUser: 'dantehemerson',
  social: [
    { title: 'Github', link: 'https://github.com/dantehemerson', icon: 'github' },
    { title: 'Twitter', link: 'https://twitter.com/dantehemerson', icon: 'twitter' },
    { title: 'Linkedin', link: 'https://linkedin.com/in/dantecalderon', icon: 'linkedin' },
    // { title: 'Twitch', link: 'https://www.twitch.tv/dantehemerson', icon: 'twitch' },
    // { title: 'Medium', link: 'https://medium.com/@dantehemerson', icon: 'medium' },
    // { title: 'Instagram', link: 'https://instagram.com/dantehemerson', icon: 'instagram' },
    // { title: 'StackOverflow', link: 'https://instagram.com/dantehemerson', icon: 'stack-overflow' },
    // { title: 'Goodreads', link: 'https://instagram.com/dantehemerson', icon: 'instagram' },
    // { title: 'FreeCodeCamp', link: 'https://instagram.com/dantehemerson', icon: 'free-code-camp' },
    // { title: 'Gitlab', link: 'https://instagram.com/dantehemerson', icon: 'gitlab' },
    // { title: 'Angellist', link: 'https://angel.co/dantehemerson', icon: 'angellist' },
    // { title: 'Codepen', link: 'https://codepen.io/dantehemerson', icon: 'codepen' },
    // { title: 'Meetup', link: 'https://www.meetup.com/es/members/256853185/', icon: 'meetup' },
    // { title: 'Pinterest', link: 'https://www.pinterest.com/dantehemerson/', icon: 'pinterest' },
    // { title: 'Steam', link: 'https://steamcommunity.com/id/dantehemerson/', icon: 'steam' },
    // { title: 'Youtube', link: 'https://www.youtube.com/channel/UCCbtGSRgh1RFYysgaZkoE0A', icon: 'youtube-play' },
  ],
  socials: {
    github: 'https://github.com/dantehemerson',
    twitter: 'https://twitter.com/dantehemerson',
    linkedin: 'https://linkedin.com/in/dantecalderon',
    dev: 'https://dev.to/dantehemerson',
    instagram: 'https://instagram.com/dantehemerson',
  },
  menu: [
    { title: 'Home', id: 'home', to: '/', icon: 'home' },
    { title: 'Blog', id: 'blog', to: '/blog', icon: 'blog' },
    { title: 'Projects', id: 'Projects', to: '/projects', icon: 'projects' },
  ],
} as const

export type SiteConfig = typeof siteConfig
